# Generated by Django 5.1.4 on 2024-12-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelApp', '0003_student_mother_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='Mr', max_length=100, null=True),
        ),
    ]
