# Generated by Django 5.1.4 on 2024-12-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelApp', '0004_alter_student_father_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
