# Generated by Django 5.1.4 on 2024-12-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('father_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
