# Generated by Django 5.1.4 on 2024-12-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCategoryApp', '0002_remove_category_target'),
        ('TaskModelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='relation',
            field=models.ManyToManyField(to='TaskCategoryApp.category'),
        ),
    ]
