# Generated by Django 5.1.4 on 2024-12-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCategoryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='target',
        ),
    ]
